{{- if and .Values.encryption.enabled (eq .Values.encryption.type "ztunnel") }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
  name: ztunnel-cilium
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: ztunnel
  template:
    metadata:
      annotations:
        prometheus.io/port: "15020"
        prometheus.io/scrape: "true"
        sidecar.istio.io/inject: "false"
      labels:
        app: ztunnel
    spec:
      hostNetwork: true
      hostPID: true
      serviceAccountName: ztunnel
      containers:
      - args:
        - proxy
        - ztunnel
        env:
        - name: USE_SPIRE
          value: "true"
        - name: SPIRE_ADMIN_ENDPOINT_SOCKET
          value: "unix:///run/spire/sockets/admin.sock"
        - name: XDS_ADDRESS
          value: "https://localhost:15012"
        - name: XDS_ROOT_CA
          value: "/etc/ztunnel/bootstrap-root.crt"
        - name: CA_ROOT_CA
          value: "/run/spire/bundle/bundle.crt"
        # - name: CA_ADDRESS
        #   value: "https://localhost:15012"
        - name: FAKE_CA
          value: "false"
        - name: RUST_LOG
          value: info
        - name: RUST_BACKTRACE
          value: "1"
        # - name: LOCAL_XDS_PATH
        #   value: "/usr/local/bin/localhost.yaml"
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.hostIP
        - name: INSTANCE_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        - name: SERVICE_ACCOUNT
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.serviceAccountName
        - name: ISTIO_META_ENABLE_HBONE
          value: "true"
        image: acnpublic.azurecr.io/prism/ztunnel:v0.1.45
        imagePullPolicy: IfNotPresent
        name: istio-proxy
        ports:
        - containerPort: 15020
          name: ztunnel-stats
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz/ready
            port: 15021
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          requests:
            cpu: 200m
            memory: 512Mi
        securityContext:
          allowPrivilegeEscalation: true
          capabilities:
            add:
            - NET_ADMIN
            - SYS_ADMIN
            - NET_RAW
            drop:
            - ALL
          privileged: false
          readOnlyRootFilesystem: true
          runAsGroup: 1337
          runAsNonRoot: false
          runAsUser: 0
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - name: spire-bundle
          mountPath: /run/spire/bundle
        - name: spire-agent-socket
          mountPath: /run/spire/sockets/admin.sock
          readOnly: false
        - mountPath: /var/run/ztunnel
          name: ztunnel-dir
        # - mountPath: /usr/local/bin
        #   name: opt
        - mountPath: /etc/ztunnel
          name: cilium-ztunnel-secrets
        - mountPath: /sys/fs/cgroup
          name: cgroup
          readOnly: true
      dnsPolicy: ClusterFirst
      nodeSelector:
        kubernetes.io/os: linux
      priorityClassName: system-node-critical
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      tolerations:
      - effect: NoSchedule
        operator: Exists
      - key: CriticalAddonsOnly
        operator: Exists
      - effect: NoExecute
        operator: Exists
      volumes:
      - name: spire-agent-socket
        hostPath:
          path: /run/spire/sockets/admin.sock
          type: Socket
      - hostPath:
          path: /var/run/cilium
          type: DirectoryOrCreate
        name: ztunnel-dir
      # - hostPath:
      #     path: /opt
      #     type: DirectoryOrCreate
      #   name: opt
      - name: cilium-ztunnel-secrets
        secret:
          secretName: cilium-ztunnel-secrets
          items:
            - key: bootstrap-root.crt
              path: bootstrap-root.crt
            - key: ca-root.crt
              path: ca-root.crt
      - hostPath:
          path: /sys/fs/cgroup
          type: Directory
        name: cgroup
      - name: spire-bundle
        configMap:
          name: spire-bundle
          items:
            - key: bundle.crt
              path: bundle.crt
  updateStrategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
{{- end }}
