// Code generated by go-swagger; DO NOT EDIT.

// Copyright Authors of Cilium
// SPDX-License-Identifier: Apache-2.0

package dnsproxy

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// GetReadyzReader is a Reader for the GetReadyz structure.
type GetReadyzReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetReadyzReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetReadyzOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 500:
		result := NewGetReadyzInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 501:
		result := NewGetReadyzNotImplemented()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /readyz] GetReadyz", response, response.Code())
	}
}

// NewGetReadyzOK creates a GetReadyzOK with default headers values
func NewGetReadyzOK() *GetReadyzOK {
	return &GetReadyzOK{}
}

/*
GetReadyzOK describes a response with status code 200, with default header values.

Standalone DNS proxy is healthy
*/
type GetReadyzOK struct {
	Payload string
}

// IsSuccess returns true when this get readyz o k response has a 2xx status code
func (o *GetReadyzOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get readyz o k response has a 3xx status code
func (o *GetReadyzOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get readyz o k response has a 4xx status code
func (o *GetReadyzOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get readyz o k response has a 5xx status code
func (o *GetReadyzOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get readyz o k response a status code equal to that given
func (o *GetReadyzOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get readyz o k response
func (o *GetReadyzOK) Code() int {
	return 200
}

func (o *GetReadyzOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /readyz][%d] getReadyzOK %s", 200, payload)
}

func (o *GetReadyzOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /readyz][%d] getReadyzOK %s", 200, payload)
}

func (o *GetReadyzOK) GetPayload() string {
	return o.Payload
}

func (o *GetReadyzOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetReadyzInternalServerError creates a GetReadyzInternalServerError with default headers values
func NewGetReadyzInternalServerError() *GetReadyzInternalServerError {
	return &GetReadyzInternalServerError{}
}

/*
GetReadyzInternalServerError describes a response with status code 500, with default header values.

Standalone DNS proxy is not healthy
*/
type GetReadyzInternalServerError struct {
	Payload string
}

// IsSuccess returns true when this get readyz internal server error response has a 2xx status code
func (o *GetReadyzInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get readyz internal server error response has a 3xx status code
func (o *GetReadyzInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get readyz internal server error response has a 4xx status code
func (o *GetReadyzInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this get readyz internal server error response has a 5xx status code
func (o *GetReadyzInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this get readyz internal server error response a status code equal to that given
func (o *GetReadyzInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the get readyz internal server error response
func (o *GetReadyzInternalServerError) Code() int {
	return 500
}

func (o *GetReadyzInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /readyz][%d] getReadyzInternalServerError %s", 500, payload)
}

func (o *GetReadyzInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /readyz][%d] getReadyzInternalServerError %s", 500, payload)
}

func (o *GetReadyzInternalServerError) GetPayload() string {
	return o.Payload
}

func (o *GetReadyzInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetReadyzNotImplemented creates a GetReadyzNotImplemented with default headers values
func NewGetReadyzNotImplemented() *GetReadyzNotImplemented {
	return &GetReadyzNotImplemented{}
}

/*
GetReadyzNotImplemented describes a response with status code 501, with default header values.

Standalone DNS proxy health status not available
*/
type GetReadyzNotImplemented struct {
	Payload string
}

// IsSuccess returns true when this get readyz not implemented response has a 2xx status code
func (o *GetReadyzNotImplemented) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get readyz not implemented response has a 3xx status code
func (o *GetReadyzNotImplemented) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get readyz not implemented response has a 4xx status code
func (o *GetReadyzNotImplemented) IsClientError() bool {
	return false
}

// IsServerError returns true when this get readyz not implemented response has a 5xx status code
func (o *GetReadyzNotImplemented) IsServerError() bool {
	return true
}

// IsCode returns true when this get readyz not implemented response a status code equal to that given
func (o *GetReadyzNotImplemented) IsCode(code int) bool {
	return code == 501
}

// Code gets the status code for the get readyz not implemented response
func (o *GetReadyzNotImplemented) Code() int {
	return 501
}

func (o *GetReadyzNotImplemented) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /readyz][%d] getReadyzNotImplemented %s", 501, payload)
}

func (o *GetReadyzNotImplemented) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /readyz][%d] getReadyzNotImplemented %s", 501, payload)
}

func (o *GetReadyzNotImplemented) GetPayload() string {
	return o.Payload
}

func (o *GetReadyzNotImplemented) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
