// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: dnsproxy.proto

package dnsproxy

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_dnsproxy_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_dnsproxy_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_dnsproxy_proto_rawDescGZIP(), []int{0}
}

func (x *Request) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type AzureFQDNMapping struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FQDN          string                 `protobuf:"bytes,1,opt,name=FQDN,proto3" json:"FQDN,omitempty"`
	IPS           [][]byte               `protobuf:"bytes,2,rep,name=IPS,proto3" json:"IPS,omitempty"`
	TTL           uint32                 `protobuf:"varint,3,opt,name=TTL,proto3" json:"TTL,omitempty"`
	ClientIp      []byte                 `protobuf:"bytes,4,opt,name=client_ip,json=clientIp,proto3" json:"client_ip,omitempty"`
	ResponseCode  uint32                 `protobuf:"varint,5,opt,name=response_code,json=responseCode,proto3" json:"response_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AzureFQDNMapping) Reset() {
	*x = AzureFQDNMapping{}
	mi := &file_dnsproxy_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AzureFQDNMapping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AzureFQDNMapping) ProtoMessage() {}

func (x *AzureFQDNMapping) ProtoReflect() protoreflect.Message {
	mi := &file_dnsproxy_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AzureFQDNMapping.ProtoReflect.Descriptor instead.
func (*AzureFQDNMapping) Descriptor() ([]byte, []int) {
	return file_dnsproxy_proto_rawDescGZIP(), []int{1}
}

func (x *AzureFQDNMapping) GetFQDN() string {
	if x != nil {
		return x.FQDN
	}
	return ""
}

func (x *AzureFQDNMapping) GetIPS() [][]byte {
	if x != nil {
		return x.IPS
	}
	return nil
}

func (x *AzureFQDNMapping) GetTTL() uint32 {
	if x != nil {
		return x.TTL
	}
	return 0
}

func (x *AzureFQDNMapping) GetClientIp() []byte {
	if x != nil {
		return x.ClientIp
	}
	return nil
}

func (x *AzureFQDNMapping) GetResponseCode() uint32 {
	if x != nil {
		return x.ResponseCode
	}
	return 0
}

type Result struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Result) Reset() {
	*x = Result{}
	mi := &file_dnsproxy_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Result) ProtoMessage() {}

func (x *Result) ProtoReflect() protoreflect.Message {
	mi := &file_dnsproxy_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Result.ProtoReflect.Descriptor instead.
func (*Result) Descriptor() ([]byte, []int) {
	return file_dnsproxy_proto_rawDescGZIP(), []int{2}
}

func (x *Result) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type FQDNSelector struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MatchName     string                 `protobuf:"bytes,1,opt,name=match_name,json=matchName,proto3" json:"match_name,omitempty"`
	MatchPattern  string                 `protobuf:"bytes,2,opt,name=match_pattern,json=matchPattern,proto3" json:"match_pattern,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FQDNSelector) Reset() {
	*x = FQDNSelector{}
	mi := &file_dnsproxy_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FQDNSelector) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FQDNSelector) ProtoMessage() {}

func (x *FQDNSelector) ProtoReflect() protoreflect.Message {
	mi := &file_dnsproxy_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FQDNSelector.ProtoReflect.Descriptor instead.
func (*FQDNSelector) Descriptor() ([]byte, []int) {
	return file_dnsproxy_proto_rawDescGZIP(), []int{3}
}

func (x *FQDNSelector) GetMatchName() string {
	if x != nil {
		return x.MatchName
	}
	return ""
}

func (x *FQDNSelector) GetMatchPattern() string {
	if x != nil {
		return x.MatchPattern
	}
	return ""
}

type DNSPolicyRule struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SelectorString string                 `protobuf:"bytes,1,opt,name=selector_string,json=selectorString,proto3" json:"selector_string,omitempty"`
	PortRules      []*FQDNSelector        `protobuf:"bytes,2,rep,name=port_rules,json=portRules,proto3" json:"port_rules,omitempty"`
	MatchLabels    []string               `protobuf:"bytes,3,rep,name=match_labels,json=matchLabels,proto3" json:"match_labels,omitempty"`
	Selections     []uint32               `protobuf:"varint,4,rep,packed,name=selections,proto3" json:"selections,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DNSPolicyRule) Reset() {
	*x = DNSPolicyRule{}
	mi := &file_dnsproxy_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DNSPolicyRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DNSPolicyRule) ProtoMessage() {}

func (x *DNSPolicyRule) ProtoReflect() protoreflect.Message {
	mi := &file_dnsproxy_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DNSPolicyRule.ProtoReflect.Descriptor instead.
func (*DNSPolicyRule) Descriptor() ([]byte, []int) {
	return file_dnsproxy_proto_rawDescGZIP(), []int{4}
}

func (x *DNSPolicyRule) GetSelectorString() string {
	if x != nil {
		return x.SelectorString
	}
	return ""
}

func (x *DNSPolicyRule) GetPortRules() []*FQDNSelector {
	if x != nil {
		return x.PortRules
	}
	return nil
}

func (x *DNSPolicyRule) GetMatchLabels() []string {
	if x != nil {
		return x.MatchLabels
	}
	return nil
}

func (x *DNSPolicyRule) GetSelections() []uint32 {
	if x != nil {
		return x.Selections
	}
	return nil
}

type DNSPolicyRules struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EndpointId    uint64                 `protobuf:"varint,1,opt,name=endpoint_id,json=endpointId,proto3" json:"endpoint_id,omitempty"`
	Port          uint32                 `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	Rules         []*DNSPolicyRule       `protobuf:"bytes,3,rep,name=rules,proto3" json:"rules,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DNSPolicyRules) Reset() {
	*x = DNSPolicyRules{}
	mi := &file_dnsproxy_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DNSPolicyRules) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DNSPolicyRules) ProtoMessage() {}

func (x *DNSPolicyRules) ProtoReflect() protoreflect.Message {
	mi := &file_dnsproxy_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DNSPolicyRules.ProtoReflect.Descriptor instead.
func (*DNSPolicyRules) Descriptor() ([]byte, []int) {
	return file_dnsproxy_proto_rawDescGZIP(), []int{5}
}

func (x *DNSPolicyRules) GetEndpointId() uint64 {
	if x != nil {
		return x.EndpointId
	}
	return 0
}

func (x *DNSPolicyRules) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *DNSPolicyRules) GetRules() []*DNSPolicyRule {
	if x != nil {
		return x.Rules
	}
	return nil
}

var File_dnsproxy_proto protoreflect.FileDescriptor

const file_dnsproxy_proto_rawDesc = "" +
	"\n" +
	"\x0ednsproxy.proto\x12\bdnsproxy\"#\n" +
	"\aRequest\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\x8c\x01\n" +
	"\x10AzureFQDNMapping\x12\x12\n" +
	"\x04FQDN\x18\x01 \x01(\tR\x04FQDN\x12\x10\n" +
	"\x03IPS\x18\x02 \x03(\fR\x03IPS\x12\x10\n" +
	"\x03TTL\x18\x03 \x01(\rR\x03TTL\x12\x1b\n" +
	"\tclient_ip\x18\x04 \x01(\fR\bclientIp\x12#\n" +
	"\rresponse_code\x18\x05 \x01(\rR\fresponseCode\"\"\n" +
	"\x06Result\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"R\n" +
	"\fFQDNSelector\x12\x1d\n" +
	"\n" +
	"match_name\x18\x01 \x01(\tR\tmatchName\x12#\n" +
	"\rmatch_pattern\x18\x02 \x01(\tR\fmatchPattern\"\xb2\x01\n" +
	"\rDNSPolicyRule\x12'\n" +
	"\x0fselector_string\x18\x01 \x01(\tR\x0eselectorString\x125\n" +
	"\n" +
	"port_rules\x18\x02 \x03(\v2\x16.dnsproxy.FQDNSelectorR\tportRules\x12!\n" +
	"\fmatch_labels\x18\x03 \x03(\tR\vmatchLabels\x12\x1e\n" +
	"\n" +
	"selections\x18\x04 \x03(\rR\n" +
	"selections\"t\n" +
	"\x0eDNSPolicyRules\x12\x1f\n" +
	"\vendpoint_id\x18\x01 \x01(\x04R\n" +
	"endpointId\x12\x12\n" +
	"\x04port\x18\x02 \x01(\rR\x04port\x12-\n" +
	"\x05rules\x18\x03 \x03(\v2\x17.dnsproxy.DNSPolicyRuleR\x05rules2\x9b\x01\n" +
	"\rAzureFQDNData\x12F\n" +
	"\x13SubscribeToDNSRules\x12\x11.dnsproxy.Request\x1a\x18.dnsproxy.DNSPolicyRules\"\x000\x01\x12B\n" +
	"\x0eUpdateMappings\x12\x1a.dnsproxy.AzureFQDNMapping\x1a\x10.dnsproxy.Result\"\x00(\x01B*Z(github.com/cilium/cilium/api/v1/dnsproxyb\x06proto3"

var (
	file_dnsproxy_proto_rawDescOnce sync.Once
	file_dnsproxy_proto_rawDescData []byte
)

func file_dnsproxy_proto_rawDescGZIP() []byte {
	file_dnsproxy_proto_rawDescOnce.Do(func() {
		file_dnsproxy_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dnsproxy_proto_rawDesc), len(file_dnsproxy_proto_rawDesc)))
	})
	return file_dnsproxy_proto_rawDescData
}

var file_dnsproxy_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_dnsproxy_proto_goTypes = []any{
	(*Request)(nil),          // 0: dnsproxy.Request
	(*AzureFQDNMapping)(nil), // 1: dnsproxy.AzureFQDNMapping
	(*Result)(nil),           // 2: dnsproxy.Result
	(*FQDNSelector)(nil),     // 3: dnsproxy.FQDNSelector
	(*DNSPolicyRule)(nil),    // 4: dnsproxy.DNSPolicyRule
	(*DNSPolicyRules)(nil),   // 5: dnsproxy.DNSPolicyRules
}
var file_dnsproxy_proto_depIdxs = []int32{
	3, // 0: dnsproxy.DNSPolicyRule.port_rules:type_name -> dnsproxy.FQDNSelector
	4, // 1: dnsproxy.DNSPolicyRules.rules:type_name -> dnsproxy.DNSPolicyRule
	0, // 2: dnsproxy.AzureFQDNData.SubscribeToDNSRules:input_type -> dnsproxy.Request
	1, // 3: dnsproxy.AzureFQDNData.UpdateMappings:input_type -> dnsproxy.AzureFQDNMapping
	5, // 4: dnsproxy.AzureFQDNData.SubscribeToDNSRules:output_type -> dnsproxy.DNSPolicyRules
	2, // 5: dnsproxy.AzureFQDNData.UpdateMappings:output_type -> dnsproxy.Result
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_dnsproxy_proto_init() }
func file_dnsproxy_proto_init() {
	if File_dnsproxy_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dnsproxy_proto_rawDesc), len(file_dnsproxy_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_dnsproxy_proto_goTypes,
		DependencyIndexes: file_dnsproxy_proto_depIdxs,
		MessageInfos:      file_dnsproxy_proto_msgTypes,
	}.Build()
	File_dnsproxy_proto = out.File
	file_dnsproxy_proto_goTypes = nil
	file_dnsproxy_proto_depIdxs = nil
}
