syntax = "proto3";

package dnsproxy;

option go_package = "github.com/cilium/cilium/api/v1/dnsproxy";

service AzureFQDNData {
    rpc SubscribeToDNSRules(Request) returns (stream DNSPolicyRules) {}
    rpc UpdateMappings(stream AzureFQDNMapping) returns (stream Result) {}
}
  
message Request {
  string message = 1;
}

message AzureFQDNMapping {
  string FQDN = 1;
  repeated bytes IPS = 2;
  uint32 TTL = 3;
  bytes client_ip = 4;
  uint32 response_code = 5;
  MetricsData metrics = 6;
  uint32 request_id = 7;
}

message MetricsData {
  ProcessingStats processing_stats = 1;
  DNSResponseData dns_response_data = 2;
  string endpoint_ip_port = 3;
  string server_addr = 4;
  uint32 server_identity = 5;
  string protocol = 6;
  bool allowed = 7;
}

message ProcessingStats {
  string err = 1;
  string data_source = 2;
}

message DNSResponseData {
  bool response = 1;
  repeated string cnames = 2;
  repeated uint32 qtypes = 3;
  repeated uint32 answer_times = 4;
}

message Result {
  bool success = 1;
  uint32 request_id = 2;
}

message FQDNSelector {
  string match_name = 1;
  string match_pattern = 2;
}

message DNSPolicyRule {
  string selector_string = 1;
  repeated FQDNSelector port_rules= 2;
  repeated string match_labels = 3;
  repeated uint32 selections = 4;
}

message DNSPolicyRules {
  uint64 endpoint_id = 1;
  uint32 port = 2;
  repeated DNSPolicyRule rules = 3;
  uint32 protocol = 4;
}