// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.1
// source: dnsproxy.proto

package dnsproxy

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FQDNData_SubscribeToDNSRules_FullMethodName = "/dnsproxy.FQDNData/SubscribeToDNSRules"
	FQDNData_UpdateMappings_FullMethodName      = "/dnsproxy.FQDNData/UpdateMappings"
)

// FQDNDataClient is the client API for FQDNData service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FQDNDataClient interface {
	SubscribeToDNSRules(ctx context.Context, in *Request, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DNSPolicyRules], error)
	UpdateMappings(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[FQDNMapping, Result], error)
}

type fQDNDataClient struct {
	cc grpc.ClientConnInterface
}

func NewFQDNDataClient(cc grpc.ClientConnInterface) FQDNDataClient {
	return &fQDNDataClient{cc}
}

func (c *fQDNDataClient) SubscribeToDNSRules(ctx context.Context, in *Request, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DNSPolicyRules], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &FQDNData_ServiceDesc.Streams[0], FQDNData_SubscribeToDNSRules_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Request, DNSPolicyRules]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FQDNData_SubscribeToDNSRulesClient = grpc.ServerStreamingClient[DNSPolicyRules]

func (c *fQDNDataClient) UpdateMappings(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[FQDNMapping, Result], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &FQDNData_ServiceDesc.Streams[1], FQDNData_UpdateMappings_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[FQDNMapping, Result]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FQDNData_UpdateMappingsClient = grpc.BidiStreamingClient[FQDNMapping, Result]

// FQDNDataServer is the server API for FQDNData service.
// All implementations should embed UnimplementedFQDNDataServer
// for forward compatibility.
type FQDNDataServer interface {
	SubscribeToDNSRules(*Request, grpc.ServerStreamingServer[DNSPolicyRules]) error
	UpdateMappings(grpc.BidiStreamingServer[FQDNMapping, Result]) error
}

// UnimplementedFQDNDataServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFQDNDataServer struct{}

func (UnimplementedFQDNDataServer) SubscribeToDNSRules(*Request, grpc.ServerStreamingServer[DNSPolicyRules]) error {
	return status.Errorf(codes.Unimplemented, "method SubscribeToDNSRules not implemented")
}
func (UnimplementedFQDNDataServer) UpdateMappings(grpc.BidiStreamingServer[FQDNMapping, Result]) error {
	return status.Errorf(codes.Unimplemented, "method UpdateMappings not implemented")
}
func (UnimplementedFQDNDataServer) testEmbeddedByValue() {}

// UnsafeFQDNDataServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FQDNDataServer will
// result in compilation errors.
type UnsafeFQDNDataServer interface {
	mustEmbedUnimplementedFQDNDataServer()
}

func RegisterFQDNDataServer(s grpc.ServiceRegistrar, srv FQDNDataServer) {
	// If the following call pancis, it indicates UnimplementedFQDNDataServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FQDNData_ServiceDesc, srv)
}

func _FQDNData_SubscribeToDNSRules_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Request)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(FQDNDataServer).SubscribeToDNSRules(m, &grpc.GenericServerStream[Request, DNSPolicyRules]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FQDNData_SubscribeToDNSRulesServer = grpc.ServerStreamingServer[DNSPolicyRules]

func _FQDNData_UpdateMappings_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(FQDNDataServer).UpdateMappings(&grpc.GenericServerStream[FQDNMapping, Result]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FQDNData_UpdateMappingsServer = grpc.BidiStreamingServer[FQDNMapping, Result]

// FQDNData_ServiceDesc is the grpc.ServiceDesc for FQDNData service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FQDNData_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dnsproxy.FQDNData",
	HandlerType: (*FQDNDataServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SubscribeToDNSRules",
			Handler:       _FQDNData_SubscribeToDNSRules_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "UpdateMappings",
			Handler:       _FQDNData_UpdateMappings_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "dnsproxy.proto",
}
