// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.1
// source: dnsproxy.proto

package dnsproxy

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AzureFQDNData_SubscribeToDNSRules_FullMethodName = "/dnsproxy.AzureFQDNData/SubscribeToDNSRules"
	AzureFQDNData_UpdateMappings_FullMethodName      = "/dnsproxy.AzureFQDNData/UpdateMappings"
)

// AzureFQDNDataClient is the client API for AzureFQDNData service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AzureFQDNDataClient interface {
	SubscribeToDNSRules(ctx context.Context, in *Request, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DNSPolicyRules], error)
	UpdateMappings(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AzureFQDNMapping, Result], error)
}

type azureFQDNDataClient struct {
	cc grpc.ClientConnInterface
}

func NewAzureFQDNDataClient(cc grpc.ClientConnInterface) AzureFQDNDataClient {
	return &azureFQDNDataClient{cc}
}

func (c *azureFQDNDataClient) SubscribeToDNSRules(ctx context.Context, in *Request, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DNSPolicyRules], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AzureFQDNData_ServiceDesc.Streams[0], AzureFQDNData_SubscribeToDNSRules_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Request, DNSPolicyRules]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AzureFQDNData_SubscribeToDNSRulesClient = grpc.ServerStreamingClient[DNSPolicyRules]

func (c *azureFQDNDataClient) UpdateMappings(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AzureFQDNMapping, Result], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AzureFQDNData_ServiceDesc.Streams[1], AzureFQDNData_UpdateMappings_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[AzureFQDNMapping, Result]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AzureFQDNData_UpdateMappingsClient = grpc.BidiStreamingClient[AzureFQDNMapping, Result]

// AzureFQDNDataServer is the server API for AzureFQDNData service.
// All implementations should embed UnimplementedAzureFQDNDataServer
// for forward compatibility.
type AzureFQDNDataServer interface {
	SubscribeToDNSRules(*Request, grpc.ServerStreamingServer[DNSPolicyRules]) error
	UpdateMappings(grpc.BidiStreamingServer[AzureFQDNMapping, Result]) error
}

// UnimplementedAzureFQDNDataServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAzureFQDNDataServer struct{}

func (UnimplementedAzureFQDNDataServer) SubscribeToDNSRules(*Request, grpc.ServerStreamingServer[DNSPolicyRules]) error {
	return status.Errorf(codes.Unimplemented, "method SubscribeToDNSRules not implemented")
}
func (UnimplementedAzureFQDNDataServer) UpdateMappings(grpc.BidiStreamingServer[AzureFQDNMapping, Result]) error {
	return status.Errorf(codes.Unimplemented, "method UpdateMappings not implemented")
}
func (UnimplementedAzureFQDNDataServer) testEmbeddedByValue() {}

// UnsafeAzureFQDNDataServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AzureFQDNDataServer will
// result in compilation errors.
type UnsafeAzureFQDNDataServer interface {
	mustEmbedUnimplementedAzureFQDNDataServer()
}

func RegisterAzureFQDNDataServer(s grpc.ServiceRegistrar, srv AzureFQDNDataServer) {
	// If the following call pancis, it indicates UnimplementedAzureFQDNDataServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AzureFQDNData_ServiceDesc, srv)
}

func _AzureFQDNData_SubscribeToDNSRules_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Request)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AzureFQDNDataServer).SubscribeToDNSRules(m, &grpc.GenericServerStream[Request, DNSPolicyRules]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AzureFQDNData_SubscribeToDNSRulesServer = grpc.ServerStreamingServer[DNSPolicyRules]

func _AzureFQDNData_UpdateMappings_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AzureFQDNDataServer).UpdateMappings(&grpc.GenericServerStream[AzureFQDNMapping, Result]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AzureFQDNData_UpdateMappingsServer = grpc.BidiStreamingServer[AzureFQDNMapping, Result]

// AzureFQDNData_ServiceDesc is the grpc.ServiceDesc for AzureFQDNData service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AzureFQDNData_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dnsproxy.AzureFQDNData",
	HandlerType: (*AzureFQDNDataServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SubscribeToDNSRules",
			Handler:       _AzureFQDNData_SubscribeToDNSRules_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "UpdateMappings",
			Handler:       _AzureFQDNData_UpdateMappings_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "dnsproxy.proto",
}
