// Code generated by go-swagger; DO NOT EDIT.

// Copyright Authors of Cilium
// SPDX-License-Identifier: Apache-2.0

package dnsproxy

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// GetReadyzOKCode is the HTTP code returned for type GetReadyzOK
const GetReadyzOKCode int = 200

/*
GetReadyzOK Standalone DNS proxy is healthy

swagger:response getReadyzOK
*/
type GetReadyzOK struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewGetReadyzOK creates GetReadyzOK with default headers values
func NewGetReadyzOK() *GetReadyzOK {

	return &GetReadyzOK{}
}

// WithPayload adds the payload to the get readyz o k response
func (o *GetReadyzOK) WithPayload(payload string) *GetReadyzOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get readyz o k response
func (o *GetReadyzOK) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetReadyzOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// GetReadyzInternalServerErrorCode is the HTTP code returned for type GetReadyzInternalServerError
const GetReadyzInternalServerErrorCode int = 500

/*
GetReadyzInternalServerError Standalone DNS proxy is not healthy

swagger:response getReadyzInternalServerError
*/
type GetReadyzInternalServerError struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewGetReadyzInternalServerError creates GetReadyzInternalServerError with default headers values
func NewGetReadyzInternalServerError() *GetReadyzInternalServerError {

	return &GetReadyzInternalServerError{}
}

// WithPayload adds the payload to the get readyz internal server error response
func (o *GetReadyzInternalServerError) WithPayload(payload string) *GetReadyzInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get readyz internal server error response
func (o *GetReadyzInternalServerError) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetReadyzInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// GetReadyzNotImplementedCode is the HTTP code returned for type GetReadyzNotImplemented
const GetReadyzNotImplementedCode int = 501

/*
GetReadyzNotImplemented Standalone DNS proxy health status not available

swagger:response getReadyzNotImplemented
*/
type GetReadyzNotImplemented struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewGetReadyzNotImplemented creates GetReadyzNotImplemented with default headers values
func NewGetReadyzNotImplemented() *GetReadyzNotImplemented {

	return &GetReadyzNotImplemented{}
}

// WithPayload adds the payload to the get readyz not implemented response
func (o *GetReadyzNotImplemented) WithPayload(payload string) *GetReadyzNotImplemented {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get readyz not implemented response
func (o *GetReadyzNotImplemented) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetReadyzNotImplemented) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(501)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
